### ISSUE TITLE
Concentration wrapper fails in iOS7

### ISSUE THREAD

**Issue by arouinfar** [phetsims/phet-metacog#11]
When loading Concentration in the Metacog wrapper in iOS 7.0.4 and 7.1/ Safari the sim immediately migrates downward off screen leaving a blank screen. This issue is not present when directly opening 1.2.0-together.3. 

Screenshot of the start of the migration off-screen:
![image](https://cloud.githubusercontent.com/assets/8419308/7462415/863b5218-f26e-11e4-8194-704b1ac98b11.jpg)

**Comment by jbphet** [comment]
I let Metacog know about this issue and have asked them if they intend to track it down.  I don't think that this one is in our court, but I'll leave it open until we hear back.  If they are deeply concerned, we may help them to investigate.  Otherwise I'll just close it.

**Comment by samreid** [comment]
The wrapper is probably setting too large of a size for the iframe.

**Comment by jbphet** [comment]
Metacog has done their ISTE demo and we didn't hear of any issues.  Since they don't seem to be concerned about mobile devices for now, and since it appears to be an issues with their wrapper, and since it is on an older version of iOS, I'm closing this.
