### ISSUE TITLE
When playing back after a previous playback, the sim iframe needs to be reloaded

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-metacog#4]
From #2, when going from playback -> playback, we need to reset the simulation--without resetting the simulation, the final state from playback 1 "leaks into" playback 2 and makes it incorrect.

Perhaps I should work with @cesarpachon to understand the messages going to the metacog listener so that I can reinitialize the playback module when it is reset for playback.

**Comment by samreid** [comment]
I proposed a solution above, but have it commented out at the moment because it looks like another issue is preventing it from working properly.  I'm seeing two `playback reset` messages in rapid succession when pressing the 'refresh' button which is causing requirejs to bail.  One is called from this code:

```js
      _toolbarPlaybackBtnReset.onclick = function(){
        if(Metacog.API.waiting) return;
        Metacog.TrainingToolbar.reset();
      };
```

and the other is called from this code:

```js
  /**
   * prepare a xhr with the proper metacog headers and invoke the send method.
   ( a prior call is required to open the connection with the method and url )
   * handles all the errors (redirect to UI error tab) and invoke the callback on success.
   * @param cb {function} callback to be invoked on success. params: data
   * @param errcb {function} callback to be invoked on errors. params: status, responseText
   * @param data {Object} Object to tokenize as JSON, or a String with a JSON value.
   * @private
   */
   Metacog.API._sendXhr = function(cb, errcb, data){
    var self = this;
     this._setupXhr(this._xhr)
      .onreadystatechange = function() {
      if (self._xhr.readyState == 4){
        self.waiting = false;
        Metacog._emit("end_api_waiting");


        if(self._xhr.status == 200 || self._xhr.status == 201 || self._xhr.status == 204){

          if(self._xhr.status == 204){
            cb({results:[]});
          }else{
            var data = JSON.parse(self._xhr.responseText);
            cb(data);
          }
```

I'm unfamiliar with the metacog implementation and not sure if one of these messages should be excluded or ignored.  Would be great to discuss with @cesarpachon.

Also, I'm not sure why requirejs would fail on two rapid loads, and this may not be a problem in the compiled version.

**Comment by samreid** [comment]
I tried building the running phet-metacog.html with a compiled version, and the problem disappeared (though the sim does flicker twice on the screen before coming up).

**Comment by samreid** [comment]
Note: I am receiving an error that a DerivedProperty value was trying to be set with the built version.  Perhaps this check is failing after uglify2?

> property.constructor.name === 'DerivedProperty'

**Comment by samreid** [comment]
I asked @jonathanolson about the above issue over skype.

**Comment by samreid** [comment]
Without understanding the problem fully, I investigated introducing a DerivedProperty type in the together API.  It seems like it solves the problem.

**Comment by samreid** [comment]
In 355d6000aa98d05ce278506a331c70077208d9ab I am reloading the playback frame when necessary.  Note that when using a non-compiled version, the 2 "restarted" messages from metacog causes an issue.

**Comment by samreid** [comment]
I'll assign this issue to @cesarpachon to investigate looking into the multiple messages from Metacog (or if those double messages have to happen for other reasons and we must work around them).

**Comment by samreid** [comment]
Another workaround we could employ is to not destroy any iframes until they have finished loading.  We could check for loading status by getting an "initialized" message from them.  We could investigate this if and only if we find that the double "restart" messages are necessary.

**Comment by cesarpachon** [comment]
I found the source of the repeated messages inside metacog code, I am testing locally before publishing a fix to the metacog library (it probably will involve a change in the minor version number)

**Comment by samreid** [comment]
It looks like work in https://github.com/phetsims/together/issues/58 may have resolved this issue (though I'm not sure why).

**Comment by cesarpachon** [comment]
The current metacog client library version is 2.0.1, that is already deployed in production and has the fix for the double triggering of reset messages.

**Comment by samreid** [comment]
I cleared my cache and verified I am no longer seeing the double restart messages.  Thanks!
