### ISSUE TITLE
Uncaught no_training_api_server_available

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-metacog#5]
I have seen this error twice recently, not sure what it means.  @cesarpachon have you seen anything like this?  The first time I saw this, I had augmented the query parameter with &emitEmptyDeltas (I'll commit that shortly) and log_tab=false.

POST http://testapi.metacog.com/training_sessions/9c0dbe2f-946d-4c82-80d1-7f0aa70f8511/events 500 (Internal Server Error)
metacog-2.0.1.js:2367 Uncaught no_training_api_server_available

**Comment by cesarpachon** [comment]
this is a controlled exception that only appears in the developer console, but did not affect the workflow (no events are lost, because they are being queued in the LocalStorage). We are working with server side team to handle better this case.
